< /$objtype/mkfile

TARG=lola
OFILES=\
	main.$O \
	text.$O \
	wind.$O \
	wctl.$O \
	fs.$O \
	util.$O \
	kbd.$O \
	time.$O \
	data.$O \
	menuhit.$O \
	deskmenu.$O \
	simple.$O

HFILES=inc.h

BIN=/$objtype/bin

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	flat.c\
	win3.c\
	win95.c\
	README\

< /sys/src/cmd/mkone
