[build]
  command = "make site"
  publish = "build/site"

[[headers]]
  for = "/assets/**/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/**/*.raw"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "no-store"
