< /$objtype/mkfile

TARG=rio
OFILES=\
	main.$O \
	text.$O \
	wind.$O \
	wctl.$O \
	fs.$O \
	util.$O \
	kbd.$O \
	time.$O \
	data.$O \
	menuhit.$O \
	deskmenu.$O \
	panel.$O \
	dialog.$O \
	deskicon.$O \
	splash.$O \
	theme.$O \
	flat.$O \
	simple.$O \
	win3.$O \
	win95.$O

HFILES=inc.h

BIN=/$objtype/bin

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	README\

< /sys/src/cmd/mkone
