</$objtype/mkfile

TARG=nsselect
KRYON=/sys/src/kryon
BIN=/$objtype/bin
OUT=$O.out

CPPFLAGS=-I$KRYON/src/platform/plan9/include -I$KRYON/include \
	-DKRYON_BACKEND_LIBDRAW -DKRYON_PLATFORM_PLAN9 -DKRYON_NATIVE_PLAN9
CFLAGS=-FTVw

OFILES=\
	nsselect.$O\

LIB=/$objtype/lib/libkryon.a /$objtype/lib/libstdio.a

all:V: $OUT

install:V: $BIN/$TARG

$BIN/$TARG: $OUT
	cp $OUT $BIN/$TARG

$OUT: $OFILES $LIB
	$LD -o $target $prereq -ldraw -lmemdraw -lthread

%.$O: %.c
	cpp -+ $CPPFLAGS $stem.c > $stem.i && $CC $CFLAGS -c $stem.i && mv $stem.i.$O $stem.$O && rm -f $stem.i

clean:V:
	rm -f *.[$OS] *.i [$OS].out $TARG
